const status = {
  SUCCESS_STATUS: 200,
  INTERNAL_SERVER_ERROR_STATUS: 500,
  NOT_FOUND: 404,
  INCORRECT_PASSWORD: 401,
  UNAUTHORIZED_USER: 401,
  SUCCESS: 1,
  ERROR: 0
};
module.exports = {
  status
};
